const ATTRIBUTE_TYPES = {
	BYTE: 5120,
	SHORT: 5122,
	UNSIGNED_BYTE: 5121,
	UNSIGNED_SHORT: 5123,
	FIXED: undefined,
	FLOAT: 5126,
};

Object.freeze(ATTRIBUTE_TYPES);

export { ATTRIBUTE_TYPES as default };
